env:
  browser: true
  es6: true
parser:
  "@typescript-eslint/parser"
extends:
  - airbnb-typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - "@typescript-eslint"
settings:
  import/extensions: [".js",".jsx",".ts",".tsx"]
  import/parsers:
    '@typescript-eslint/parser': [".ts",".tsx"]
  import/resolver':
    node:
      extensions: [".js",".jsx",".ts",".tsx"]
rules:
  no-multiple-empty-lines:
    - error
    - max: 1
  lines-between-class-members: off
  no-restricted-syntax: off
  arrow-parens:
    - error
    - as-needed
